SQL> SET LONG 1000000
SQL> SET LONGCHUNKSIZE 1000000
SQL> SET PAGESIZE 0
SQL> SET LINESIZE 32767
SQL> SET FEEDBACK OFF
SQL> SET HEADING OFF
SQL> SET ECHO OFF
SQL> SET VERIFY OFF
SQL> SET TRIMSPOOL ON
SQL> SELECT DBMS_METADATA.GET_DDL('TABLE', table_name)
  2  FROM USER_TABLES
  3  WHERE table_name IN (
  4  'DEPARTMENT',
  5  'PATIENT',
  6  'DOCTOR',
  7  'APP_USER',
  8  'APPOINTMENT',
  9  'ENCOUNTER',
 10  'VITAL_SIGN',
 11  'DIAGNOSIS',
 12  'PRESCRIPTION',
 13  'MEDICATION',
 14  'PRESCRIPTION_ITEM',
 15  'SERVICE',
 16  'INVOICE',
 17  'INVOICE_ITEM',
 18  'PAYMENT'
 19  )
 20  ORDER BY table_name;

  CREATE TABLE "CLINIC"."APPOINTMENT"
   (	"APPOINTMENT_ID" NUMBER NOT NULL ENABLE,
	"PATIENT_ID" NUMBER NOT NULL ENABLE,
	"DOCTOR_ID" NUMBER NOT NULL ENABLE,
	"APPOINTMENT_DATE" DATE NOT NULL ENABLE,
	"START_TIME" TIMESTAMP (6),
	"END_TIME" TIMESTAMP (6),
	"STATUS" VARCHAR2(30) DEFAULT 'SCHEDULED' NOT NULL ENABLE,
	"BOOKING_REASON" VARCHAR2(500),
	"NOTES" VARCHAR2(1000),
	"CREATION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "CK_APPOINTMENT_STATUS" CHECK (status IN ('SCHEDULED','CONFIRMED','COMPLETED','CANCELLED','NO_SHOW')) ENABLE,
	 CONSTRAINT "PK_APPOINTMENT" PRIMARY KEY ("APPOINTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_APPOINTMENT_PATIENT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "CLINIC"."PATIENT" ("PATIENT_ID") ENABLE,
	 CONSTRAINT "FK_APPOINTMENT_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
	  REFERENCES "CLINIC"."DOCTOR" ("DOCTOR_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."APP_USER"
   (	"USER_ID" NUMBER NOT NULL ENABLE,
	"USERNAME" VARCHAR2(100) NOT NULL ENABLE,
	"PASSWORD_HASH" VARCHAR2(255) NOT NULL ENABLE,
	"USER_ROLE" VARCHAR2(50) NOT NULL ENABLE,
	"DOCTOR_ID" NUMBER,
	"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"CREATION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "CK_APP_USER_ACTIVE" CHECK (active IN (0,1)) ENABLE,
	 CONSTRAINT "PK_APP_USER" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UQ_APP_USER_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UQ_APP_USER_DOCTOR" UNIQUE ("DOCTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_APP_USER_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
	  REFERENCES "CLINIC"."DOCTOR" ("DOCTOR_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."DEPARTMENT"
   (	"DEPARTMENT_ID" NUMBER NOT NULL ENABLE,
	"DEPARTMENT_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500),
	"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 CONSTRAINT "CK_DEPARTMENT_ACTIVE" CHECK (active IN (0,1)) ENABLE,
	 CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY ("DEPARTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UQ_DEPARTMENT_NAME" UNIQUE ("DEPARTMENT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."DIAGNOSIS"
   (	"DIAGNOSIS_ID" NUMBER NOT NULL ENABLE,
	"ENCOUNTER_ID" NUMBER NOT NULL ENABLE,
	"DIAGNOSIS" VARCHAR2(1000) NOT NULL ENABLE,
	"DIAGNOSIS_TYPE" VARCHAR2(100),
	"NOTES" VARCHAR2(1000),
	 CONSTRAINT "PK_DIAGNOSIS" PRIMARY KEY ("DIAGNOSIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_DIAGNOSIS_ENCOUNTER" FOREIGN KEY ("ENCOUNTER_ID")
	  REFERENCES "CLINIC"."ENCOUNTER" ("ENCOUNTER_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."DOCTOR"
   (	"DOCTOR_ID" NUMBER NOT NULL ENABLE,
	"DEPARTMENT_ID" NUMBER NOT NULL ENABLE,
	"DOCTOR_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"SPECIALTY" VARCHAR2(150),
	"PHONE" VARCHAR2(30),
	"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 CONSTRAINT "CK_DOCTOR_ACTIVE" CHECK (active IN (0,1)) ENABLE,
	 CONSTRAINT "PK_DOCTOR" PRIMARY KEY ("DOCTOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_DOCTOR_DEPARTMENT" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "CLINIC"."DEPARTMENT" ("DEPARTMENT_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."ENCOUNTER"
   (	"ENCOUNTER_ID" NUMBER NOT NULL ENABLE,
	"PATIENT_ID" NUMBER NOT NULL ENABLE,
	"DOCTOR_ID" NUMBER NOT NULL ENABLE,
	"APPOINTMENT_ID" NUMBER,
	"ENCOUNTER_DATETIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"CHIEF_COMPLAINT" VARCHAR2(1000),
	"NOTES" VARCHAR2(2000),
	"STATUS" VARCHAR2(30) DEFAULT 'OPEN' NOT NULL ENABLE,
	"CREATION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	 CONSTRAINT "CK_ENCOUNTER_STATUS" CHECK (status IN ('OPEN','COMPLETED','CANCELLED')) ENABLE,
	 CONSTRAINT "PK_ENCOUNTER" PRIMARY KEY ("ENCOUNTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UQ_ENCOUNTER_APPOINTMENT" UNIQUE ("APPOINTMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_ENCOUNTER_PATIENT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "CLINIC"."PATIENT" ("PATIENT_ID") ENABLE,
	 CONSTRAINT "FK_ENCOUNTER_DOCTOR" FOREIGN KEY ("DOCTOR_ID")
	  REFERENCES "CLINIC"."DOCTOR" ("DOCTOR_ID") ENABLE,
	 CONSTRAINT "FK_ENCOUNTER_APPOINTMENT" FOREIGN KEY ("APPOINTMENT_ID")
	  REFERENCES "CLINIC"."APPOINTMENT" ("APPOINTMENT_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."INVOICE"
   (	"INVOICE_ID" NUMBER NOT NULL ENABLE,
	"INVOICE_NUMBER" VARCHAR2(50) NOT NULL ENABLE,
	"PATIENT_ID" NUMBER NOT NULL ENABLE,
	"ENCOUNTER_ID" NUMBER,
	"INVOICE_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"SUBTOTAL" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE,
	"DISCOUNT" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE,
	"TOTAL_AMOUNT" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE,
	"STATUS" VARCHAR2(30) DEFAULT 'UNPAID' NOT NULL ENABLE,
	"NOTES" VARCHAR2(1000),
	 CONSTRAINT "CK_INV_SUB" CHECK (subtotal>=0) ENABLE,
	 CONSTRAINT "CK_INV_DIS" CHECK (discount>=0) ENABLE,
	 CONSTRAINT "CK_INV_TOT" CHECK (total_amount>=0) ENABLE,
	 CONSTRAINT "CK_INV_STA" CHECK (status IN ('UNPAID','PARTIAL','PAID','CANCELLED')) ENABLE,
	 CONSTRAINT "PK_INVOICE" PRIMARY KEY ("INVOICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UQ_INV_NUM" UNIQUE ("INVOICE_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_INV_PAT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "CLINIC"."PATIENT" ("PATIENT_ID") ENABLE,
	 CONSTRAINT "FK_INV_ENC" FOREIGN KEY ("ENCOUNTER_ID")
	  REFERENCES "CLINIC"."ENCOUNTER" ("ENCOUNTER_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."INVOICE_ITEM"
   (	"INVOICE_ITEM_ID" NUMBER NOT NULL ENABLE,
	"INVOICE_ID" NUMBER NOT NULL ENABLE,
	"SERVICE_ID" NUMBER NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500),
	"QUANTITY" NUMBER(10,2) DEFAULT 1 NOT NULL ENABLE,
	"UNIT_PRICE" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE,
	"DISCOUNT" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE,
	"TOTAL_AMOUNT" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE,
	 CONSTRAINT "CK_II_QTY" CHECK (quantity>0) ENABLE,
	 CONSTRAINT "CK_II_PRI" CHECK (unit_price>=0) ENABLE,
	 CONSTRAINT "CK_II_DIS" CHECK (discount>=0) ENABLE,
	 CONSTRAINT "CK_II_TOT" CHECK (total_amount>=0) ENABLE,
	 CONSTRAINT "PK_INV_ITEM" PRIMARY KEY ("INVOICE_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_II_INV" FOREIGN KEY ("INVOICE_ID")
	  REFERENCES "CLINIC"."INVOICE" ("INVOICE_ID") ENABLE,
	 CONSTRAINT "FK_II_SRV" FOREIGN KEY ("SERVICE_ID")
	  REFERENCES "CLINIC"."SERVICE" ("SERVICE_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."MEDICATION"
   (	"MEDICATION_ID" NUMBER NOT NULL ENABLE,
	"MEDICATION_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"CONCENTRATION" VARCHAR2(100),
	"DOSAGE_FORM" VARCHAR2(100),
	"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 CONSTRAINT "CK_MEDICATION_ACTIVE" CHECK (active IN (0,1)) ENABLE,
	 CONSTRAINT "PK_MEDICATION" PRIMARY KEY ("MEDICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."PATIENT"
   (	"PATIENT_ID" NUMBER NOT NULL ENABLE,
	"FIRST_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"FAMILY_NAME" VARCHAR2(100) NOT NULL ENABLE,
	"GENDER" VARCHAR2(10),
	"BIRTH_DATE" DATE,
	"PHONE" VARCHAR2(30),
	"CREATION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(500),
	 CONSTRAINT "CK_PATIENT_GENDER" CHECK (gender IN ('MALE','FEMALE')) ENABLE,
	 CONSTRAINT "CK_PATIENT_ACTIVE" CHECK (active IN (0,1)) ENABLE,
	 CONSTRAINT "PK_PATIENT" PRIMARY KEY ("PATIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."PAYMENT"
   (	"PAYMENT_ID" NUMBER NOT NULL ENABLE,
	"INVOICE_ID" NUMBER NOT NULL ENABLE,
	"AMOUNT" NUMBER(12,2) NOT NULL ENABLE,
	"PAYMENT_METHOD" VARCHAR2(50) NOT NULL ENABLE,
	"PAYMENT_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"REFERENCE_NUMBER" VARCHAR2(100),
	"NOTES" VARCHAR2(1000),
	 CONSTRAINT "CK_PAY_AMT" CHECK (amount>0) ENABLE,
	 CONSTRAINT "CK_PAY_MET" CHECK (payment_method IN ('CASH','CARD','BANK_TRANSFER','OTHER')) ENABLE,
	 CONSTRAINT "PK_PAYMENT" PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_PAY_INV" FOREIGN KEY ("INVOICE_ID")
	  REFERENCES "CLINIC"."INVOICE" ("INVOICE_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."PRESCRIPTION"
   (	"PRESCRIPTION_ID" NUMBER NOT NULL ENABLE,
	"ENCOUNTER_ID" NUMBER NOT NULL ENABLE,
	"PRESCRIPTION_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"NOTES" VARCHAR2(1000),
	 CONSTRAINT "PK_PRESCRIPTION" PRIMARY KEY ("PRESCRIPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_PRESCRIPTION_ENCOUNTER" FOREIGN KEY ("ENCOUNTER_ID")
	  REFERENCES "CLINIC"."ENCOUNTER" ("ENCOUNTER_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."PRESCRIPTION_ITEM"
   (	"PRESCRIPTION_ITEM_ID" NUMBER NOT NULL ENABLE,
	"PRESCRIPTION_ID" NUMBER NOT NULL ENABLE,
	"MEDICATION_ID" NUMBER NOT NULL ENABLE,
	"DOSE" VARCHAR2(100),
	"NUMBER_OF_TIMES" NUMBER(5,0),
	"DURATION" VARCHAR2(100),
	"USAGE_METHOD" VARCHAR2(200),
	"INSTRUCTIONS" VARCHAR2(1000),
	 CONSTRAINT "CK_PRI_NUM" CHECK (number_of_times IS NULL OR number_of_times > 0) ENABLE,
	 CONSTRAINT "PK_PRI" PRIMARY KEY ("PRESCRIPTION_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_PRI_PRE" FOREIGN KEY ("PRESCRIPTION_ID")
	  REFERENCES "CLINIC"."PRESCRIPTION" ("PRESCRIPTION_ID") ENABLE,
	 CONSTRAINT "FK_PRI_MED" FOREIGN KEY ("MEDICATION_ID")
	  REFERENCES "CLINIC"."MEDICATION" ("MEDICATION_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."SERVICE"
   (	"SERVICE_ID" NUMBER NOT NULL ENABLE,
	"SERVICE_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(500),
	"PRICE" NUMBER(12,2) DEFAULT 0 NOT NULL ENABLE,
	"ACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE,
	 CONSTRAINT "CK_SERVICE_PRICE" CHECK (price>=0) ENABLE,
	 CONSTRAINT "CK_SERVICE_ACTIVE" CHECK (active IN (0,1)) ENABLE,
	 CONSTRAINT "PK_SERVICE" PRIMARY KEY ("SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"



  CREATE TABLE "CLINIC"."VITAL_SIGN"
   (	"VITAL_SIGN_ID" NUMBER NOT NULL ENABLE,
	"ENCOUNTER_ID" NUMBER NOT NULL ENABLE,
	"WEIGHT" NUMBER(6,2),
	"HEIGHT" NUMBER(6,2),
	"SYSTOLIC_BP" NUMBER(5,2),
	"DIASTOLIC_BP" NUMBER(5,2),
	"BLOOD_SUGAR" NUMBER(7,2),
	"OXYGEN_SATURATION" NUMBER(5,2),
	"PULSE" NUMBER(5,2),
	"TEMPERATURE" NUMBER(5,2),
	"RECORDED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	 CONSTRAINT "CK_VITAL_WEIGHT" CHECK (weight IS NULL OR weight > 0) ENABLE,
	 CONSTRAINT "CK_VITAL_HEIGHT" CHECK (height IS NULL OR height > 0) ENABLE,
	 CONSTRAINT "CK_VITAL_OXYGEN" CHECK (oxygen_saturation IS NULL OR oxygen_saturation BETWEEN 0 AND 100) ENABLE,
	 CONSTRAINT "PK_VITAL_SIGN" PRIMARY KEY ("VITAL_SIGN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "UQ_VITAL_SIGN_ENCOUNTER" UNIQUE ("ENCOUNTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_VITAL_SIGN_ENCOUNTER" FOREIGN KEY ("ENCOUNTER_ID")
	  REFERENCES "CLINIC"."ENCOUNTER" ("ENCOUNTER_ID") ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"


SQL> 
SQL> SPOOL OFF
